import uuid
from datetime import UTC, datetime, timedelta

from sqlalchemy.orm import Session

from app.models.feature_modules import (
    Appointment,
    FamilyMember,
    HealthTask,
    LabResult,
    MedicationReminder,
    MentalHealthScreening,
    PregnancyRecord,
    Prescription,
    SymptomEntry,
    VaccinationRecord,
)
from app.models.user import User
from app.services.clinical_tools_service import ClinicalToolsService


class CareWorkflowService:
    def __init__(self, db: Session) -> None:
        self.db = db
        self.tools = ClinicalToolsService()

    def create_prescription(self, *, doctor: User, payload: dict) -> Prescription:
        rx = Prescription(id=str(uuid.uuid4()), doctor_id=doctor.id, **payload)
        self.db.add(rx)
        self.db.commit()
        self.db.refresh(rx)
        return rx

    def book_appointment(self, *, patient_id: str, payload: dict) -> Appointment:
        appt = Appointment(id=str(uuid.uuid4()), patient_id=patient_id, **payload)
        if not appt.booking_reference:
            appt.booking_reference = f"REQ-{uuid.uuid4().hex[:8].upper()}"
        self.db.add(appt)
        self.db.commit()
        self.db.refresh(appt)
        return appt

    def add_family_member(self, *, owner_id: str, payload: dict) -> FamilyMember:
        member = FamilyMember(id=str(uuid.uuid4()), owner_id=owner_id, **payload)
        self.db.add(member)
        self.db.commit()
        self.db.refresh(member)
        return member

    def create_medication_reminder(self, *, patient_id: str, payload: dict) -> MedicationReminder:
        reminder = MedicationReminder(id=str(uuid.uuid4()), patient_id=patient_id, **payload)
        self.db.add(reminder)
        self.db.commit()
        self.db.refresh(reminder)
        return reminder

    def track_symptoms(self, *, patient_id: str, symptoms: str, severity: int, duration: str) -> SymptomEntry:
        entry = SymptomEntry(
            id=str(uuid.uuid4()),
            patient_id=patient_id,
            symptoms=symptoms,
            severity=severity,
            duration=duration,
            triage_result=self.tools.symptom_triage(symptoms=symptoms, severity=severity),
        )
        self.db.add(entry)
        self.db.commit()
        self.db.refresh(entry)
        return entry

    def save_lab_result(self, *, patient_id: str, test_name: str, value: float, unit: str) -> LabResult:
        result = LabResult(
            id=str(uuid.uuid4()),
            patient_id=patient_id,
            test_name=test_name,
            value=value,
            unit=unit,
            interpretation=self.tools.interpret_lab(test_name=test_name, value=value, unit=unit),
        )
        self.db.add(result)
        self.db.commit()
        self.db.refresh(result)
        return result

    def add_vaccination(self, *, patient_id: str, payload: dict) -> VaccinationRecord:
        record = VaccinationRecord(id=str(uuid.uuid4()), patient_id=patient_id, **payload)
        self.db.add(record)
        self.db.commit()
        self.db.refresh(record)
        return record

    def add_pregnancy(self, *, patient_id: str, lmp_date: str, notes: str = "") -> PregnancyRecord:
        estimated_due_date = ""
        try:
            lmp = datetime.fromisoformat(lmp_date)
            estimated_due_date = (lmp + timedelta(days=280)).date().isoformat()
        except ValueError:
            pass
        record = PregnancyRecord(
            id=str(uuid.uuid4()),
            patient_id=patient_id,
            lmp_date=lmp_date,
            estimated_due_date=estimated_due_date,
            notes=notes,
        )
        self.db.add(record)
        self.db.commit()
        self.db.refresh(record)
        return record

    def save_mental_health_screening(
        self,
        *,
        patient_id: str,
        screening_type: str,
        score: int,
    ) -> MentalHealthScreening:
        screening = MentalHealthScreening(
            id=str(uuid.uuid4()),
            patient_id=patient_id,
            screening_type=screening_type,
            score=score,
            risk_level=self.tools.mental_health_risk(score=score, screening_type=screening_type),
        )
        self.db.add(screening)
        self.db.commit()
        self.db.refresh(screening)
        return screening

    def generate_health_tasks(self, *, patient_id: str) -> list[HealthTask]:
        task = HealthTask(
            id=str(uuid.uuid4()),
            patient_id=patient_id,
            task_type="annual_checkup",
            title="Schedule annual preventive health checkup",
            description="Generated by health score/reminder engine.",
            priority="medium",
            due_date=datetime.now(UTC).date().isoformat(),
        )
        self.db.add(task)
        self.db.commit()
        return [task]
